
name: Build and Deploy Docker Container

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: ledger/docs

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Login to Container registry.
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
          images: getledger/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: getledger/documentation:latest
          labels: ${{ steps.meta.outputs.labels }}
